### ISSUE TITLE
Ksyxis Mod causes world loading to get stuck at 15%.

### ISSUE THREAD

**Issue by Nomispacetime** [TeamPeril/Sculk-Hoard#48]
Hi, I believe I'm not the only one experiencing an issue where the world loads and stops at 15%. It's one of the core mods in my modpack, so if possible, could you take a look at your mod to find the problem, please? It seems possible that the issue may stem from a specific line of code (a very specific line that seems like an odd hack), as mentioned by @chickenlipsdev. This issue appears to have started after version 0.7.17.

The mod that is causing problems is Ksyxis. Is it possible to make it compatible, please? 

Thank you.

**Comment by Mikeatron-User** [comment]
I don't even know where to even begin to try and fix this. What line is ChickenLipsDev referring to?

**Comment by Scott-Tatham** [comment]
Hey I'm ChickenLipsDev,
Sorry if things were a little vague. To help clarify, I believe the issue was introduced in commit cdea1cf5df13b971bd15b9dc4cfb0881ffe2c5ec where chunk (0, 0) is force loaded on world load. I absolutely could be wrong, but looking at the changes between versions this seemed to be the most likely culprit for the issue. I'm not sure why it is causing an issue with Ksysix, but I was wondering if there may be an alternative approach to allow both mods to run together.

**Comment by Mikeatron-User** [comment]
> Hey I'm ChickenLipsDev, Sorry if things were a little vague. To help clarify, I believe the issue was introduced in commit [cdea1cf](https://github.com/TeamPeril/Sculk-Horde/commit/cdea1cf5df13b971bd15b9dc4cfb0881ffe2c5ec) where chunk (0, 0) is force loaded on world load. I absolutely could be wrong, but looking at the changes between versions this seemed to be the most likely culprit for the issue. I'm not sure why it is causing an issue with Ksysix, but I was wondering if there may be an alternative approach to allow both mods to run together.

It is unfortunately necessary. I see no other way to change this.
