### ISSUE TITLE
Main structure generation cutoff

### ISSUE THREAD

**Issue by ThePiekar** [TeamPeril/Sculk-Hoard#57]
I'm playing sculk horde in combination with several terra-blender based generation mods, which shouldn't affect world elevation.

The main structure located at 0 0 generates too low, making the most bottom chamber be cut off by the world bottom.

This makes the mod essentially unplayable due to the inability to start the horde event.

Minecraft forge 1.20.1

**Comment by nicolaslesquoy** [comment]
Hi, I also have this issue where the main structure does not generate at all because I added a mod that changes the world height below -64. If you want to spawn the Horde, you can go into creative mode and put the brain node directly in your world and it starts the event. I don't know if any other activities are modified by having no tomb.

**Comment by Mikeatron-User** [comment]
I will look for a way to possibly fix this, though I'm unsure if I will be able to.
