### ISSUE TITLE
I have already submitted this and it has been invalidated but listen, please.

### ISSUE THREAD

**Issue by davros364** [TeamPeril/Sculk-Hoard#69]
whenever i use the modpack version(the one that has the custom title screen andnot the standalone sculk horde that is supposed to be combined with other mods) i can get to the title screen, but all i can do is press singleplayer, upon which it will say "saving world" and promptly crash putting me back to the launcher. here is some evidence:

![Screenshot 2024-09-10 151155](https://github.com/user-attachments/assets/73682447-14be-4e94-aa0c-79857e497e7a)

![Screenshot 2024-09-10 151234](https://github.com/user-attachments/assets/d7ec2b93-7c74-4bc2-96a8-05605ce920ee)

![Screenshot 2024-09-10 151245](https://github.com/user-attachments/assets/fa93e478-651f-413c-ae59-7d0f3a054c68)

i am on the latest version of minecraft, curseforge, AND the modpack and nothing is added on as you can see here:

![Screenshot 2024-09-10 151708](https://github.com/user-attachments/assets/badd8843-b53d-47bc-a851-aa3b8ab312ca)

i am only able to play it succesfully with the standalone version aka this one:

![Screenshot 2024-09-10 151826](https://github.com/user-attachments/assets/a4968807-31c7-414f-8b5a-0a90d1e80954)

as for the crash log here is the launcher's notification and the log itself:

![Screenshot 2024-09-10 151306](https://github.com/user-attachments/assets/a20feead-72b9-4bc9-b9bc-f92accb22b13)

[crash-2024-09-04_13.50.41-client (1).txt](https://github.com/user-attachments/files/16955679/crash-2024-09-04_13.50.41-client.1.txt)

i submitted the log by itself, but they said there was no crash in it. I mean the title SAYS crash report. if you didnt get access to it for some reason heres a link to a google doc with it all copy and pasted directly from my notepad.

[---- Minecraft Crash Report ----.pdf](https://github.com/user-attachments/files/16955700/----.Minecraft.Crash.Report.----.pdf)

just do not dismiss this again please.
Davros364
⇐{=====>

**Comment by davros364** [comment]
sorry i forgot to add this but i could not get a screenshot of the "saving world" screen as it crashed immediantly and it is too fast for me to screenshot it in time. i tried to capture a vidio of it happening, but im new to that kind of thing and couldnt do it myself.
just please take this seriously, k?

**Comment by Mikeatron-User** [comment]
I will investigate this

**Comment by davros364** [comment]
thx so much

**Comment by ryleu** [comment]
sassy label is hilarious

**Comment by davros364** [comment]
> sassy label is hilarious

Im not sure if its serious or not though.

**Comment by ScreamingMC** [comment]
Putting a crash report in a pdf is a war crime

**Comment by ScreamingMC** [comment]
<img width="985" height="733" alt="Image" src="https://github.com/user-attachments/assets/eac20ed2-6887-464e-ab5a-dccefae0ab95" />

by saving world you mean **this** screen?

minecraft shows saving world before crashing because it's trying to save your game before it closes, even if outside a world because it doesn't check if world isn't `null`

## Where the “Saving world” message comes from
The message is triggered inside this method:

```
this.m_91394_();
```

And inside that method, `\net\minecraft\client\minecraft.java`:

> “this.m_91320_(new GenericDirtMessageScreen(Component.m_237115_("menu.savingLevel")));”

That line **always runs**, even if no world is loaded.

This is the key:  
Minecraft does not check whether a world exists before showing the “Saving world” dirt screen.

---

## Why Minecraft does this  
### 1. The crash handler is designed to be *safe*, not *smart*
The crash handler tries to:

- free memory  
- stop the integrated server  
- save the world  
- show a dirt screen  
- then crash  

It does this **unconditionally**, because checking “is a world loaded?” is risky during a crash — the game state may be corrupted.

So instead of branching logic, Mojang uses a simple rule:

> “Always attempt to save the world if a crash happens.”

If no world is loaded, the save attempt simply does nothing, but the UI still shows the message.

---

## ### 2. The dirt screen is used as a fallback UI  
The dirt screen (“Saving world”) is a generic emergency UI.  
It is used for:

- saving worlds  
- loading worlds  
- shutting down servers  
- crash cleanup  

It’s not actually tied to world saving — it’s just the only “safe” screen the client can show during a crash.

---

## ### 3. The crash handler doesn’t know the game state anymore  
During a crash, the client may be in a partially invalid state:

- world may be null  
- server may be half‑running  
- resources may be half‑loaded  

Trying to check `if (world != null)` could itself cause another crash.

So Mojang avoids conditional logic and simply runs:

```
this.m_91320_(new GenericDirtMessageScreen("Saving world"));
```

as a guaranteed safe fallback.

---

## Summary  
Minecraft shows “Saving world” on crash even when you’re not in a world because:

- The crash handler always calls the world‑saving routine  
- The dirt screen is a generic emergency UI  
- Conditional checks are avoided during crashes  
- The message is misleading, but harmless  

It’s not actually saving anything — it’s just showing the only safe screen available.

**Comment by davros364** [comment]
i lowkey havent played sculk horde in a while so wasnt expecting an email.
whatever it was i wasa having an issue with was fixed anyway so you can
close whatever this is abnout

**Comment by ScreamingMC** [comment]
crash report in a pdf is just a war crime, also that was an explanation

**Comment by ScreamingMC** [comment]
if you want to record it easily, if you have windows then you can just windows + shift + s, select the 📷 icon, select an area of minecraft tab (not full screen), it's preinstalled. you don't need obs, that's an overkill.
