### ISSUE TITLE
Multiple Sculk Tombs / Ancient Sculk Nodes Spawning with C2ME installed.

### ISSUE THREAD

**Issue by tallubhai** [TeamPeril/Sculk-Hoard#89]
I launched a test world and checked (0,0) for the Sculk Tomb. Inside, I found 2 tombs - one fully generated, and a second one that looks to have been partially generated and then overwritten by the other one. Due to this, I have 2 Ancient Nodes in my world. 

![2024-12-09_23 42 15](https://github.com/user-attachments/assets/269f3cb7-ba07-4591-b1b1-2e86880cb3c6)
![2024-12-09_23 42 34](https://github.com/user-attachments/assets/52230455-5d00-4a36-befc-256499d9bcc8)
![2024-12-09_23 42 44](https://github.com/user-attachments/assets/9de6b981-0be6-47d3-a3c2-9f6f10cd7fb6)
![2024-12-09_23 48 32](https://github.com/user-attachments/assets/2625a21d-1872-4dcd-ad92-119107e4652e)
![2024-12-09_23 48 47](https://github.com/user-attachments/assets/93da1564-f5f9-4191-9b44-c002210cece7)

This happened right after I installed C2ME (Concurrent Chuck Management Engine), via Sinytra Connector. It may be an unintended side effect of C2ME's method of generating chunks. This is taken directly from their github page: 

"C2ME does not sacrifice vanilla functionality or behavior, or alter the vanilla world generation in the name of raw speed by default. However, due to the [non-determinism of vanilla world generation](https://bugs.mojang.com/browse/MC-55596), worlds will vary significantly run-to-run even with the same seed. This is not a bug on our side."

I am using the latest version available for 1.20.1 for all these mods.
[latest.log](https://github.com/user-attachments/files/18075218/latest.log)

**Comment by tallubhai** [comment]
I tested the same seed with C2ME installed, and it happened again. However, the same seed without C2ME generates normally. 
I tested a different seed with C2ME installed, and I once again had 2 Sculk Tombs - one split in half, the other fully generated.

**Comment by TeamPeril** [comment]
Ahh, multi-threading mods, the bane of my modding career. I will investigate to see if there is any way for me to fix this.

The reason it spawns two is because I use a boolean variable to check whether the tomb has spawned. This works fine on single threaded world generation, but defiantly is causing this issue for multi-threaded world gen. My initial idea is to maybe store in the save data instead if the tomb has been spawned, but I fear a race condition with that. We'll see what works out.
